title: "Sensible Adventures"
author: "Greg Wilson"
email: "gvwilson@third-bit.com"
domain: "http://sensibleadventures.com"
repo: "https://github.com/gvwilson/sensibleadventures"
repository: <USERNAME>/<PROJECT>
exclude:
  - misc
  - princess-bear
  - shudarga
  - "*.csv"
  - "*.docx"
  - "*.odt"
  - "*.pdf"
  - "*.txt"
