title: Sensible Adventures
subtitle: "Some of my stories aren't true, but these are all true stories"
url: https://sensibleadventures.com
repository: gvwilson/sensibleadventures

markdown: kramdown
highlighter: rouge

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - vendor/bundle
  - misc
  - "*.csv"
  - "*.docx"
  - "*.odt"
  - "*.pdf"
  - "*.txt"

permalink: pretty
paginate: 5
paginate_path: /blog/:num

blog:
  truncated_preview: false

sass:
  sass_dir: _sass
  style: :compressed

author:
  name: Greg Wilson
  url: third-bit.com
  email: gvwilson@third-bit.com
  github: https://github.com/gvwilson
  twitter: https://twitter.com/gvwilson
  linkedin: https://www.linkedin.com/in/greg-wilson-a26510b6/

plugins:
  - jekyll-coffeescript
  - jekyll-paginate
  - jekyll-gist
